// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBytp1q0SwH0naGnW4mO8cawIKhsb1R4o',
    appId: '1:135966369505:web:68e4d425c3134f6afe39a0',
    messagingSenderId: '135966369505',
    projectId: 'covid-19-4ddbb',
    authDomain: 'covid-19-4ddbb.firebaseapp.com',
    storageBucket: 'covid-19-4ddbb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZphfXHgri1pSDjKqb10j4uYZGaTuvcH4',
    appId: '1:135966369505:android:fc7a4e86251a744cfe39a0',
    messagingSenderId: '135966369505',
    projectId: 'covid-19-4ddbb',
    storageBucket: 'covid-19-4ddbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLp2zBqLu5_95-1Et1WA20LuuPLKjdhoY',
    appId: '1:135966369505:ios:dd2494ef8e7d06acfe39a0',
    messagingSenderId: '135966369505',
    projectId: 'covid-19-4ddbb',
    storageBucket: 'covid-19-4ddbb.appspot.com',
    iosClientId: '135966369505-4f7e52m7364kaahniv5mo4np1d8dcbha.apps.googleusercontent.com',
    iosBundleId: 'com.example.covid19',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLp2zBqLu5_95-1Et1WA20LuuPLKjdhoY',
    appId: '1:135966369505:ios:dd2494ef8e7d06acfe39a0',
    messagingSenderId: '135966369505',
    projectId: 'covid-19-4ddbb',
    storageBucket: 'covid-19-4ddbb.appspot.com',
    iosClientId: '135966369505-4f7e52m7364kaahniv5mo4np1d8dcbha.apps.googleusercontent.com',
    iosBundleId: 'com.example.covid19',
  );
}
